from django.urls import path

from .views import *

urlpatterns = [
    path('', home, name='home'),
    path('about/', about, name='about'),
    path('contact/', ContactFormView.as_view(), name='contact'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('password-change/', PasswordChange.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDone.as_view(), name='password_change_done'),
    path('register/', register, name='register'),
    path('edit_user/', edit_user, name='edit_user'),
    path('start_budget/', start_budget, name='start_budget'),
    path('edit_budget/', edit_budget, name='edit_budget'),
    path('show_budget/', show_budget, name='show_budget'),
    path('budget_users/', budget_users, name='budget_users'),
    path('remove_user_from_budget/<int:user_id>/<path:return_url>/', remove_user_from_budget,
         name='remove_user_from_budget'),
    path('no_account/', no_account, name='no_account'),
    path('add_account/', AddAccount.as_view(), name='add_account'),
    path('edit_account/<int:account_id>/', EditAccount.as_view(), name='edit_account'),
    path('delete_account/<int:account_id>/', DeleteAccount.as_view(), name='delete_account'),
    path('projects/', Projects.as_view(), name='projects'),
    path('add_project/', AddProject.as_view(), name='add_project'),
    path('edit_project/<int:project_id>/', EditProject.as_view(), name='edit_project'),
    path('delete_project/<int:project_id>/', DeleteProject.as_view(), name='delete_project'),
    path('budget_objects/', BudgetObjects.as_view(), name='budget_objects'),
    path('add_budget_object/', AddBudgetObject.as_view(), name='add_budget_object'),
    path('edit_budget_object/<int:budget_object_id>/', EditBudgetObject.as_view(), name='edit_budget_object'),
    path('delete_budget_object/<int:budget_object_id>/', DeleteBudgetObject.as_view(), name='delete_budget_object'),
    path('account_transactions/<int:account_id>/', AccountTransactions.as_view(), name='account_transactions'),
    path('add_transaction/<int:account_id>/<path:return_url>/', add_transaction, name='add_transaction'),
    path('edit_transaction/<int:transaction_id>/<path:return_url>/', edit_transaction, name='edit_transaction'),
    path('delete_transaction/<int:transaction_id>/<path:return_url>/', DeleteTransaction.as_view(),
         name='delete_transaction'),
    path('manage_transaction_category/<int:transaction_id>/<path:return_url>/', manage_transaction_category,
         name='manage_transaction_category'),
    path('set_join_between_transactions/<int:transaction_id>/<path:return_url>/', set_join_between_transactions,
         name='set_join_between_transactions'),
    path('account_transactions_for_join/<int:transaction_id>/<path:return_url>/', AccountTransactionsForJoin.as_view(),
         name='account_transactions_for_join'),
    path('join_confirmation_between_transactions/<int:sender_id>/<int:receiver_id>/<path:return_url>/',
         join_confirmation_between_transactions, name='join_confirmation_between_transactions'),
    path('delete_join_between_transactions/<int:transaction_id>/<path:return_url>/', delete_join_between_transactions,
         name='delete_join_between_transactions'),
    path('balances_recalculation/<int:budget_id>/<path:return_url>/', balances_recalculation,
         name='balances_recalculation'),
    path('account_transactions_without_join/<int:budget_id>/<path:return_url>/', account_transactions_without_join,
         name='account_transactions_without_join'),
    path('load_transactions/<int:account_id>/<path:return_url>/', load_transactions, name='load_transactions'),
    path('annual_budget/<int:year>/<int:currency_id>/', annual_budget, name='annual_budget'),
    path('edit_budget_register/', edit_budget_register, name='edit_budget_register'),
    path('autoplanning_budget/<int:budget_id>/<int:budget_year>/<path:return_url>/', autoplanning_budget,
         name='autoplanning_budget'),
    path('current_state/<int:currency_id>/<int:month_shift>/', current_state, name='current_state'),
    path('account_transactions_in_category_period/'
         '<int:budget_id>/<int:category_id>/<int:year>/<int:month>/<int:currency_id>/<path:return_url>/',
         AccountTransactionsInCategoryPeriod.as_view(), name='account_transactions_in_category_period'),
]
