# Generated by Django 4.1.7 on 2023-03-07 18:46

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Наименование бюджета')),
                ('secret_key', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Секретное слово')),
                ('digit_rounding', models.IntegerField(choices=[(2, 'x xxx xxx,xx - до сотых'), (1, 'x xxx xxx,x0 - до десятых'), (0, 'x xxx xxx,00 - до единиц'), (-1, 'x xxx xx0,00 - до десятков'), (-2, 'x xxx x00,00 - до сотен'), (-3, 'x xxx 000,00 - до тысяч'), (-4, 'x xx0 000,00 - до десятков тысяч'), (-5, 'x x00 000,00 - до сотен тысяч')], default=-2, verbose_name='Округление плановых значений')),
                ('start_budget_month', models.IntegerField(choices=[(None, '<не выбран>'), (1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], default=11, verbose_name='Месяц начала планирования бюджета следующего года')),
                ('end_budget_month', models.IntegerField(choices=[(None, '<не выбран>'), (1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь'), (0, 'нет ограничения')], default=2, verbose_name='Месяц окончания планирования бюджета текущего года')),
            ],
            options={
                'verbose_name': 'Бюджет',
                'verbose_name_plural': 'Бюджеты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Валюта')),
                ('iso_code', models.CharField(db_index=True, max_length=3, unique=True, verbose_name='ISO код')),
                ('numeric_code', models.CharField(max_length=3, unique=True, verbose_name='Числовой код')),
                ('entity', models.CharField(max_length=500, verbose_name='Страны использования')),
                ('is_frequently_used', models.BooleanField(default=True, verbose_name='Часто используемая')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'ordering': ['iso_code'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='Фото')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('time_zone', models.DecimalField(choices=[(Decimal('-12.00'), '(UTC-12:00) Линия перемены дат'), (Decimal('-11.00'), '(UTC-11:00) Время в формате UTC -11'), (Decimal('-10.00'), '(UTC-10:00) Гавайи'), (Decimal('-9.00'), '(UTC-09:00) Аляска'), (Decimal('-8.00'), '(UTC-08:00) Тихоокеанское время (США и Канада)'), (Decimal('-7.00'), '(UTC-07:00) Горное время (США и Канада)'), (Decimal('-6.00'), '(UTC-06:00) Центральное время (США и Канада), Мехико'), (Decimal('-5.00'), '(UTC-05:00) Восточное время (США и Канада), Богота, Лима'), (Decimal('-4.00'), '(UTC-04:00) Атлантическое время (Канада), Каракас, Ла-Пас'), (Decimal('-3.50'), '(UTC-03:30) Ньюфаундленд'), (Decimal('-3.00'), '(UTC-03:00) Бразилиа, Буэнос-Айрес'), (Decimal('-2.00'), '(UTC-02:00) Время в формате UTC -02'), (Decimal('-1.00'), '(UTC-01:00) Азорские острова'), (Decimal('0.00'), '(UTC) Время Западной Европы, Дублин, Эдинбург, Лиссабон, Лондон'), (Decimal('1.00'), '(UTC+01:00) Амстердам, Берлин, Брюссель, Копенгаген, Мадрид, Париж, Рим'), (Decimal('2.00'), '(UTC+02:00) Вильнюс, Иерусалим, Каир, Калининград, Киев, Рига, Таллин, Хельсинки'), (Decimal('3.00'), '(UTC+03:00) Багдад, Минск, Москва, Санкт-Петербург, Стамбул'), (Decimal('3.50'), '(UTC+03:30) Тегеран'), (Decimal('4.00'), '(UTC+04:00) Абу-Даби, Баку, Ереван, Самара, Тбилиси'), (Decimal('4.50'), '(UTC+04:30) Кабул'), (Decimal('5.00'), '(UTC+05:00) Ашхабад, Душанбе, Екатеринбург, Исламабад, Ташкент'), (Decimal('5.50'), '(UTC+05:30) Колката, Мумбаи, Нью-Дели, Ченнай'), (Decimal('5.75'), '(UTC+05:45) Катманду'), (Decimal('6.00'), '(UTC+06:00) Алматы, Астана, Дакка, Омск'), (Decimal('7.00'), '(UTC+07:00) Бангкок, Джакарта, Красноярск, Новосибирск, Томск, Ханой'), (Decimal('8.00'), '(UTC+08:00) Гонконг, Иркутск, Пекин, Улан-Батор, Урумчи, Чунцин'), (Decimal('9.00'), '(UTC+09:00) Осака, Пхеньян, Саппоро, Сеул, Токио, Якутск'), (Decimal('9.50'), '(UTC+09:30) Аделаида, Дарвин'), (Decimal('10.00'), '(UTC+10:00) Владивосток, Канберра, Мельбурн, Сидней'), (Decimal('11.00'), '(UTC+11:00) Магадан, Сахалин, Соломоновы о-ва, Новая Каледония'), (Decimal('12.00'), '(UTC+12:00) Веллингтон, Окленд, Петропавловск-Камчатский, Фиджи')], decimal_places=2, default=0.0, max_digits=5, verbose_name='Часовой пояс для времени операций')),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.budget', verbose_name='Бюджет семьи')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профиль',
                'ordering': ['user'],
            },
        ),
        migrations.AddField(
            model_name='budget',
            name='base_currency_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base_currency_1', to='main.currency', verbose_name='Основная валюта'),
        ),
        migrations.AddField(
            model_name='budget',
            name='base_currency_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base_currency_2', to='main.currency', verbose_name='Дополнительная валюта'),
        ),
        migrations.AddField(
            model_name='budget',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Владелец бюджета'),
        ),
    ]
