# Generated by Django 4.1.7 on 2023-03-09 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_accountturnover_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[(None, '<не выбран>'), ('Персона', 'Персона'), ('Недвижимость', 'Недвижимость'), ('Транспорт', 'Транспорт'), ('Питомец', 'Питомец'), ('Бизнес', 'Бизнес')], max_length=15, verbose_name='Тип объекта')),
                ('name', models.CharField(max_length=25, verbose_name='Имя объекта')),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.budget', verbose_name='Бюджет')),
            ],
            options={
                'verbose_name': 'Объект бюджета',
                'verbose_name_plural': 'Объекты бюджета',
                'ordering': ['budget', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('is_project_completed', models.BooleanField(default=False, verbose_name='Проект завершен?')),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.budget', verbose_name='Бюджет')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['budget', 'is_project_completed'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('type', models.CharField(choices=[('INC', 'Доход'), ('EXP', 'Расход')], max_length=3, verbose_name='Тип')),
                ('item', models.CharField(db_index=True, default='??', max_length=10, verbose_name='Статья')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.budget', verbose_name='Только для бюджета')),
                ('budget_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.budgetobject', verbose_name='Объект бюджета')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='main.category', verbose_name='Родительская категория')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Добавивший категорию в систему')),
            ],
            options={
                'verbose_name': 'Категория доходов/расходов',
                'verbose_name_plural': 'Категории доходов/расходов',
                'ordering': ['item'],
            },
        ),
        migrations.CreateModel(
            name='BudgetRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_year', models.IntegerField(verbose_name='Год бюджета')),
                ('budget_month', models.IntegerField(choices=[(None, '<не выбран>'), (1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], verbose_name='Месяц бюджета')),
                ('planned_amount_base_cur_1', models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='План в основной базовой валюте')),
                ('planned_amount_base_cur_2', models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='План в дополнительной базовой валюте')),
                ('actual_amount_base_cur_1', models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Факт в основной базовой валюте')),
                ('actual_amount_base_cur_2', models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Факт в дополнительной базовой валюте')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.budget', verbose_name='Бюджет')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Статья бюджета')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Регистр бюджета',
                'verbose_name_plural': 'Регистры бюджета',
                'ordering': ['budget', 'budget_year', 'budget_month', 'category', 'project'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['budget', 'is_project_completed'], name='p__budget_is_completed_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('budget', 'name'), name='project__budget_name_unique'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['type', 'item', 'budget'], name='category__type_item_budget_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['budget', 'name'], name='category__budget_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('budget', 'name'), name='category__budget_name_unique'),
        ),
        migrations.AddIndex(
            model_name='budgetregister',
            index=models.Index(fields=['budget', 'budget_year', 'budget_month', 'category', 'project'], name='br__bud_year_month_cat_pr_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetobject',
            index=models.Index(fields=['budget', 'name'], name='budget_object__budget_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='budgetobject',
            constraint=models.UniqueConstraint(fields=('budget', 'name'), name='budget_object__budget_name_unique'),
        ),
    ]
